### ISSUE TITLE
ShipmentState::forShipment(<trunkrsNr>) returns all null values

### ISSUE THREAD

**Issue by JSRM99** [Trunkrs/Trunkrs-SDK-PHP#37]
**Trunkrs SDK version(s) affected**: 2.1.4
**PHP version(s) affected**: 7.3

**Description**  
The function `ShipmentState::forShipment(<trunkrsNr>)` gives back only null values.

**How to reproduce**  
Call the function and try to get the status code for example.

**Additional context**  
After looking in to the code and dumping the `RequestHandler` response and the `ResultUnwrapper` result, it looks like the result is an empty array. For more info see screenshot of debug info:
![image](https://user-images.githubusercontent.com/37828702/108999737-032d9d80-76a3-11eb-962a-8a974eb6a6e3.png)

**Comment by fean** [comment]
Hey Juup! 🙂 

Thanks for your patience so far! 🙂 
Good catch! This is because the response is an array, it shouldn't be tho!

I'll log a ticket with the back-end crew and will keep you in the loop!

You could use the `Shipment::find($trunkrsNr)` in the meantime to get the state of a shipment.

**Comment by JSRM99** [comment]
Hi @fean,

Thanks for the workaround! 
We will make use of the `Shipment::find()` in the meanwhile.

**Comment by fean** [comment]
This has been solved on the production version of the API.

**Comment by tuimz** [comment]
Just to add, this issue still remains for us. Latest version of package.
